package SistemaProductos;
/**
 *
 * @author bryanortega
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        UsuarioIncorrecto.setVisible(false);
        NoVer.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Salir = new javax.swing.JLabel();
        TxtUsuario = new javax.swing.JTextField();
        BtnLogin = new javax.swing.JButton();
        LbUsuario = new javax.swing.JLabel();
        UsuarioIncorrecto = new javax.swing.JLabel();
        LbContraseña = new javax.swing.JLabel();
        TxtPassword = new javax.swing.JPasswordField();
        Ver = new javax.swing.JLabel();
        NoVer = new javax.swing.JLabel();
        ImagenUser = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(66, 60, 110));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setBackground(new java.awt.Color(204, 0, 0));
        Salir.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Salir.setText("X");
        Salir.setBorder(null);
        Salir.setOpaque(true);
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalirMouseExited(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 50, 40));

        TxtUsuario.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        TxtUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TxtUsuario.setToolTipText("INGRESE SU USUARIO");
        TxtUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(TxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 111, 283, -1));

        BtnLogin.setBackground(new java.awt.Color(39, 110, 248));
        BtnLogin.setFont(new java.awt.Font("Marker Felt", 0, 18)); // NOI18N
        BtnLogin.setForeground(new java.awt.Color(0, 0, 1));
        BtnLogin.setText("INICIAR SESION");
        BtnLogin.setActionCommand("");
        BtnLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        BtnLogin.setBorderPainted(false);
        BtnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnLoginMouseExited(evt);
            }
        });
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 319, 208, 37));

        LbUsuario.setFont(new java.awt.Font("Marker Felt", 0, 18)); // NOI18N
        LbUsuario.setText("Usuario");
        jPanel1.add(LbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 85, -1, -1));

        UsuarioIncorrecto.setFont(new java.awt.Font("Marker Felt", 0, 12)); // NOI18N
        UsuarioIncorrecto.setForeground(new java.awt.Color(204, 0, 0));
        UsuarioIncorrecto.setText("Usuario o Contraseña incorrecto. Vuelve a intentarlo");
        jPanel1.add(UsuarioIncorrecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 245, -1, -1));

        LbContraseña.setFont(new java.awt.Font("Marker Felt", 0, 18)); // NOI18N
        LbContraseña.setText("Contraseña");
        jPanel1.add(LbContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 183, -1, -1));

        TxtPassword.setFont(new java.awt.Font("AppleGothic", 0, 18)); // NOI18N
        TxtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(TxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 209, 283, -1));

        Ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SistemaProductos/IMAGENES/ver-2.png"))); // NOI18N
        Ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerMouseClicked(evt);
            }
        });
        jPanel1.add(Ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, 30));

        NoVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SistemaProductos/IMAGENES/no-visible-2.png"))); // NOI18N
        NoVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NoVerMouseClicked(evt);
            }
        });
        jPanel1.add(NoVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 420, 440));

        ImagenUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SistemaProductos/IMAGENES/IMAGE.LOGIN.png"))); // NOI18N
        getContentPane().add(ImagenUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 350, 440));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SistemaProductos/IMAGENES/Fonodo.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_SalirMouseClicked

    private void SalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseEntered
        Salir.setBackground(new java.awt.Color(255, 51, 51));
    }//GEN-LAST:event_SalirMouseEntered

    private void SalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseExited
        Salir.setBackground(new java.awt.Color(204, 0, 0));
    }//GEN-LAST:event_SalirMouseExited

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        String usuario = "admin";
        String contraseña = "12345";
        String pass = new String(TxtPassword.getPassword()); //variable para retornar el get password en el field.

        Escritorio desktop = new Escritorio(); //objeto de la clase escritorio

        if (TxtUsuario.getText().isEmpty() || pass.isEmpty()) { // Sentencia si hay espacios vacios muestra mensaje en pantalla.
            UsuarioIncorrecto.setVisible(true); // Var si cumple, muestra mensaje en pantalla.
        } else if (TxtUsuario.getText().equals(usuario) &&pass.equals(contraseña)) { //Sentencia si el usuario y contraseña son correctos.
            desktop.setVisible(true); //objeto si cumple la condicion, muestra el panel del escritorio.
            this.dispose(); // cierra la ventana de login.hshshshshhshsshsh
        }

    }//GEN-LAST:event_BtnLoginActionPerformed

    private void BtnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLoginMouseEntered
        BtnLogin.setBackground(new java.awt.Color(39, 80, 248));
    }//GEN-LAST:event_BtnLoginMouseEntered

    private void BtnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLoginMouseExited
        BtnLogin.setBackground(new java.awt.Color(39, 110, 248));
    }//GEN-LAST:event_BtnLoginMouseExited

    private void VerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerMouseClicked
        Ver.setVisible(false);
        NoVer.setVisible(true);
        TxtPassword.setEchoChar((char)0);
    }//GEN-LAST:event_VerMouseClicked

    private void NoVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoVerMouseClicked
        Ver.setVisible(true);
        NoVer.setVisible(false);
        TxtPassword.setEchoChar('*');
    }//GEN-LAST:event_NoVerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogin;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel ImagenUser;
    private javax.swing.JLabel LbContraseña;
    private javax.swing.JLabel LbUsuario;
    private javax.swing.JLabel NoVer;
    private javax.swing.JLabel Salir;
    private javax.swing.JPasswordField TxtPassword;
    private javax.swing.JTextField TxtUsuario;
    private javax.swing.JLabel UsuarioIncorrecto;
    private javax.swing.JLabel Ver;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
